name: Link-check
on:
  schedule:
    - cron: '0 1 * * *'  # 1 am everyday
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linksafe
        uses: TechWiz-3/linksafe@fast
        env:
            TOKEN: ${{ secrets.TOKEN }}
